/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "uart.h"
#include <stdio.h>
#include <stdint.h>
#include <stm32f1xx.h>
#include "tim.h"
#include "exti.h"

int main(void)
{
	PC13_EXTI_init();
	PA2_uart_tx_init();
}

static void exti_callback()
{
	printf("Tuan vo cung dep trai !\n");
}
void EXTI15_10_IRQHandler(void)
{
	if (EXTI->PR & EXTI_PR_PR13)
	{
		// clear the PR flag
		EXTI->PR |= EXTI_PR_PR13;
		// Do something ...
		exti_callback();
	}
}
